# Generated by Django 4.2.9 on 2024-01-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_alter_sites_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='status',
            field=models.CharField(editable=False, max_length=3, null=True),
        ),
    ]
