# Generated by Django 4.2.9 on 2024-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_sites_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
