# Generated by Django 4.2.9 on 2024-01-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_alter_sites_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='status',
            field=models.CharField(default='400', editable=False, max_length=3),
        ),
    ]
