# Generated by Django 4.2.9 on 2024-02-02 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_rename_userid_sites_user_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sites',
            options={'verbose_name_plural': 'Sites'},
        ),
        migrations.AddField(
            model_name='sites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sites',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
